import os
import sys
import json
import argparse
import importlib
import gymnasium as gym
import numpy as np
import time
from stable_baselines3 import TD3
from stable_baselines3.common.noise import NormalActionNoise
from eval import evaluate_model, make_env, validate_reward_spec, DEFAULT_ENV_ID


def write_failure_results(gene_id, start_time, message, stats_dir=None):
    """Record invalid fitness for generated models that cannot be evaluated."""
    train_time = time.time() - start_time
    script_dir = os.path.dirname(os.path.abspath(__file__))
    results_dir = os.path.join(script_dir, "results")
    os.makedirs(results_dir, exist_ok=True)
    with open(os.path.join(results_dir, f"{gene_id}_results.csv"), "w") as f:
        f.write(
            "mean_reward,std_reward,train_time,param_count,mean_distance,mean_control_cost,foot_contact_0,foot_contact_1,mean_return_forward,mean_return_healthy,mean_return_ctrl\n"
        )
        f.write(f"-999999.0,0.0,{train_time},999999999,0.0,0.0,0.0,0.0,0.0,0.0,0.0")

    if stats_dir:
        os.makedirs(stats_dir, exist_ok=True)
        stats_path = os.path.join(stats_dir, f"{gene_id}_stats.json")
        with open(stats_path, "w", encoding="utf-8") as f:
            json.dump(
                {
                    "gene_id": gene_id,
                    "status": "failed",
                    "error": message,
                    "train_time_sec": train_time,
                    "mean_reward": -999999.0,
                    "std_reward": 0.0,
                    "param_count": 999999999,
                },
                f,
                indent=2,
            )

    print(f"ERROR evaluating generated model: {message}")
    print(f"Mean reward: -999999.0, Std: 0.0, Time: {train_time:.1f}s")
    print("Job Done")


def main(
    gene_id,
    env_id=DEFAULT_ENV_ID,
    timesteps=500000,
    eval_episodes=None,
    eval_max_steps=None,
    model_dir="sota/MujocoRL/trained_models",
    stats_dir="sota/MujocoRL/stats",
):
    start_time = time.time()

    try:
        module = importlib.import_module(f"models.network_{gene_id}")
        policy_kwargs = module.get_policy_kwargs()
        td3_kwargs = module.get_td3_kwargs()
    except Exception as e:
        write_failure_results(gene_id, start_time, repr(e), stats_dir)
        return

    # Extract the policy class and remove it from policy_kwargs
    # so it doesn't get passed twice to TD3
    policy_class = policy_kwargs.pop("policy_class", "MlpPolicy")

    print(f"Environment: {env_id}")
    env = make_env(env_id)

    # The fitness function is the episode return, so a mis-specified reward
    # silently invalidates every gene. Fail loudly instead.
    problems = validate_reward_spec(env)
    if problems:
        env.close()
        write_failure_results(
            gene_id, start_time,
            "fitness spec mismatch: " + "; ".join(problems), stats_dir)
        return

    # Generated by Claude
    try:
        # Gaussian exploration noise N(0, sigma_a) added to the deterministic
        # actor's actions while collecting experience (TD3, Alg. 2 line 7).
        exploration_noise = float(td3_kwargs.pop("exploration_noise", 0.1))
        if exploration_noise > 0 and "action_noise" not in td3_kwargs:
            n_actions = env.action_space.shape[-1]
            td3_kwargs["action_noise"] = NormalActionNoise(
                mean=np.zeros(n_actions), sigma=exploration_noise * np.ones(n_actions))

        # For small smoke-test runs, make sure some gradient updates happen;
        # otherwise every step is spent in the random-action warm-up phase.
        if td3_kwargs.get("learning_starts", 100) >= timesteps:
            td3_kwargs["learning_starts"] = max(timesteps // 2, 1)

        model = TD3(
            policy=policy_class,
            env=env,
            policy_kwargs=policy_kwargs,  # remaining kwargs like net_arch
            **td3_kwargs
        )
    except Exception as e:
        # If the LLM-generated architecture is broken, write error results and exit
        write_failure_results(gene_id, start_time, repr(e), stats_dir)
        env.close()
        return

    # Generated by Claude
    # Count only the actor: it is the controller that gets deployed and that the
    # paper reports sizes for. model.policy also holds the twin critics and all
    # target networks, which would inflate the count several-fold.
    param_count = sum(p.numel() for p in model.actor.parameters())

    try:
        model.learn(total_timesteps=timesteps)
        os.makedirs(model_dir, exist_ok=True)
        model_path = os.path.join(model_dir, f"{gene_id}.zip")
        model.save(model_path)

        # Evaluate using eval.py
        if eval_episodes is None:
            num_eval_episodes = 1 if timesteps <= 10000 else 10
        else:
            num_eval_episodes = eval_episodes
        if eval_max_steps is None:
            max_eval_steps = 200 if timesteps <= 10000 else 1000
        else:
            max_eval_steps = eval_max_steps

        mean_reward, std_reward, rewards, metrics = evaluate_model(
            model, env, num_episodes=num_eval_episodes, max_steps=max_eval_steps
        )
    except Exception as e:
        write_failure_results(gene_id, start_time, repr(e), stats_dir)
        env.close()
        return
    train_time = time.time() - start_time

    # MAP-Elites behaviour descriptors: the proportion of steps each foot spent
    # on the ground (Nilsson & Cully, GECCO '21). See src/cfg/constants_Mujoco.py.
    foot_contact_0 = float(metrics.get("foot_contact_0", 0.0))
    foot_contact_1 = float(metrics.get("foot_contact_1", 0.0))
    # Reported for analysis; no longer used as descriptors.
    mean_distance = float(metrics.get("mean_distance", 0.0))
    mean_control_cost = float(metrics.get("mean_control_cost", 0.0))
    # Fitness decomposition: F = forward + healthy + ctrl (ctrl is negative).
    mean_return_forward = float(metrics.get("mean_return_forward", 0.0))
    mean_return_healthy = float(metrics.get("mean_return_healthy", 0.0))
    mean_return_ctrl = float(metrics.get("mean_return_ctrl", 0.0))

    # Save results under the SOTA_ROOT/results directory (where run_improved.py expects them)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    results_dir = os.path.join(script_dir, "results")
    os.makedirs(results_dir, exist_ok=True)
    with open(os.path.join(results_dir, f"{gene_id}_results.csv"), "w") as f:
        f.write(
            "mean_reward,std_reward,train_time,param_count,mean_distance,mean_control_cost,foot_contact_0,foot_contact_1,mean_return_forward,mean_return_healthy,mean_return_ctrl\n"
        )
        f.write(
            f"{mean_reward},{std_reward},{train_time},{param_count},"
            f"{mean_distance},{mean_control_cost},"
            f"{foot_contact_0},{foot_contact_1},"
            f"{mean_return_forward},{mean_return_healthy},{mean_return_ctrl}"
        )

    os.makedirs(stats_dir, exist_ok=True)
    stats_path = os.path.join(stats_dir, f"{gene_id}_stats.json")
    with open(stats_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "gene_id": gene_id,
                "env_id": env_id,
                "algorithm": "TD3",
                "timesteps": timesteps,
                "num_eval_episodes": num_eval_episodes,
                "max_eval_steps": max_eval_steps,
                "train_time_sec": train_time,
                "mean_reward": mean_reward,
                "std_reward": std_reward,
                "param_count": param_count,
                "mean_distance": mean_distance,
                "mean_control_cost": mean_control_cost,
                "foot_contact_0": foot_contact_0,
                "foot_contact_1": foot_contact_1,
                "foot_geom_names": metrics.get("foot_geom_names", []),
                "mean_return_forward": mean_return_forward,
                "mean_return_healthy": mean_return_healthy,
                "mean_return_ctrl": mean_return_ctrl,
                "reward_decomposition_error": metrics.get("reward_decomposition_error", 0.0),
                "score_band": metrics.get("score_band", ""),
                "model_path": model_path,
                "rewards": rewards,
                "distances": metrics.get("distances", []),
                "control_costs": metrics.get("control_costs", []),
                "foot_contacts_0": metrics.get("foot_contacts_0", []),
                "foot_contacts_1": metrics.get("foot_contacts_1", []),
            },
            f,
            indent=2,
        )

    print(
        "Mean reward: "
        f"{mean_reward}, Std: {std_reward}, Params: {param_count}, "
        f"Distance: {mean_distance}, CtrlCost: {mean_control_cost}, "
        f"FootContact: ({foot_contact_0:.3f}, {foot_contact_1:.3f}), "
        f"Time: {train_time:.1f}s"
    )
    print(
        f"Fitness F = forward {mean_return_forward:.2f}"
        f" + alive {mean_return_healthy:.2f}"
        f" + ctrl {mean_return_ctrl:.4f}"
        f"  [{metrics.get('score_band', '')}]"
    )
    print(f"Saved model: {model_path}")
    print(f"Saved stats: {stats_path}")
    print("Job Done")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train RL agent with evolved network")
    parser.add_argument("-network", type=str, required=True,
                        help='Module path like "models.network_XXXX"')
    parser.add_argument("-env", type=str, default=DEFAULT_ENV_ID,
                        help="Gymnasium environment id (e.g. Walker2d-v5)")
    parser.add_argument("-timesteps", type=int, default=500000,
                        help="Total training timesteps")
    parser.add_argument("-eval_episodes", type=int, default=None,
                        help="Optional number of evaluation episodes")
    parser.add_argument("-eval_max_steps", type=int, default=None,
                        help="Optional max steps per evaluation episode")
    parser.add_argument("-model_dir", type=str, default="sota/MujocoRL/trained_models",
                        help="Directory to save trained model zip")
    parser.add_argument("-stats_dir", type=str, default="sota/MujocoRL/stats",
                        help="Directory to save evaluation stats json")
    args = parser.parse_args()

    # Extract gene_id from module path: "models.network_XXXX" -> "XXXX"
    gene_id = args.network.replace("models.network_", "")

    main(
        gene_id,
        env_id=args.env,
        timesteps=args.timesteps,
        eval_episodes=args.eval_episodes,
        eval_max_steps=args.eval_max_steps,
        model_dir=args.model_dir,
        stats_dir=args.stats_dir,
    )
